name: Deploy Streamlit to HF Space

on:
  push:
    branches:
      - main  # adapte selon ta branche principale

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main repo
      uses: actions/checkout@v3

    - name: Setup git to use token
      run: git config --global credential.helper store

    - name: Clone HF Space repo
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
      run: |
        git clone https://${HF_TOKEN}@huggingface.co/spaces/NicoFena/Covid_Radio_DL hf-space

    - name: Copy src/streamlit content to HF Space
      run: |
        rsync -av src/streamlit/ hf-space/

    - name: Commit and push changes to HF Space
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
      run: |
        cd hf-space
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Update Space from main repo" || echo "No changes to commit"
        git push https://${HF_TOKEN}@huggingface.co/spaces/NicoFena/Covid_Radio_DL HEAD:main

